## A basic introduction to NumPy's einsum
http://ajcr.net/Basic-guide-to-einsum/

In [2]:
import numpy as np

### Dot multiplication of matrices

In [5]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

![einsum cover][einsum1]

[einsum1]:http://localhost:8888/files/Frontier_Artificial_Intelligence_2017S1S2/NumpyTraining/pics/eins1.png

##### 0 dimension

In [31]:
np.einsum('ij,jk->',A,B) #(), 0 dimension

numpy.int64

##### 1 dimension

In [45]:
np.einsum('ij,jk->i',A,B) #(3,), 1 dimension

array([ 6, 12, 30])

In [46]:
np.einsum('ij,jk->j',A,B) #(3,), 1 dimension

array([ 8, 16, 24])

In [47]:
np.einsum('ij,jk->k',A,B) #(3,), 1 dimension

array([16, 24,  8])

##### 2 dimensions

In [123]:
#np.einsum('ij,jk->ik', A, B), the function doesn’t construct a 3D array and then sum,

In [125]:
np.einsum('ij,jk->ij',A,B) #(i,j), 2 dimensions

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 5, 10, 15]])

In [126]:
np.einsum('ij,jk->jk',A,B) #(i,k), 2 dimensions

array([[0, 8, 0],
       [8, 8, 0],
       [8, 8, 8]])

In [122]:
# NumPy will take the labels that appeared once and arrange them in alphabetical order
np.einsum('ij,jk->ik',A,B)
# np.einsum('ij,jk',A,B) #the same as np.einsum('ij,jk->ik',A,B)

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [16]:
np.einsum('ij,jk->ik',A,B).sum() #the same with 0 dimension

48

##### 3 dimensions

In [40]:
np.einsum('ij,jk->ijk',A,B) #(i,j,k), 3 dimensions

array([[[0, 1, 0],
        [1, 1, 0],
        [1, 1, 1]],

       [[0, 2, 0],
        [2, 2, 0],
        [2, 2, 2]],

       [[0, 5, 0],
        [5, 5, 0],
        [5, 5, 5]]])

In [96]:
#^*^ other alignments of the 3 dimensions 

### Einsum for 1D arrays

Let A and B be two 1D arrays of compatible shapes (meaning the lengths of the axes we pair together either equal, or one of them has length 1

In [64]:
A = np.array([1, 2, 3])
B = np.array([0, 1, 2])



![einsum2 pic][einsum2]

[einsum2]:http://localhost:8888/files/Frontier_Artificial_Intelligence_2017S1S2/NumpyTraining/pics/eins2.png

In [92]:
np.einsum('i',A) #view of A; A

array([1, 2, 3])

In [91]:
np.einsum('i->',A) #sum of A; sum(A)

6

In [89]:
np.einsum('i,i->i',A, B) #element-wise multi of A and B; A*B

array([0, 2, 6])

In [72]:
np.einsum('i,i',A, B) #inner product (NumPy will take the labels that appeared once and arrange them in alphabetical order)
# np.einsum('i,i->',A, B) #inner product; np.inner(A,B)

8

In [82]:
np.einsum('i,j->ij',A, B) #outer product; np.outer(A,B)

array([[0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [93]:
np.einsum('i,j->',A, B)  #sum of all elements of the outer product of A and B

18

In [94]:
np.einsum('i,j->i',A, B) #sum of all elements of outer(A,B) on axis 1

array([3, 6, 9])

In [95]:
np.einsum('i,j->j',A, B) #sum of all elements of outer(A,B) on axis 0

array([ 0,  6, 12])

### Einsum for 2D arrays

In [97]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

![einsum3 pic][einsum3]

[einsum3]:http://localhost:8888/files/Frontier_Artificial_Intelligence_2017S1S2/NumpyTraining/pics/eins3.png

In [98]:
np.einsum('ij',A) #view

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

In [99]:
np.einsum('ji',A) #transpose

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

In [105]:
np.einsum('ii->i',A) #elements in the diagonal line

array([1, 2, 5])

In [107]:
np.einsum('ii->',A) #trace, sum of all diagonal elements (into 0-dimensional sum)
# np.einsum('ii',A) #trace

8

In [106]:
np.einsum('ij->',A) #sum of all elemnts (into 0-dimensional sum)

24

In [109]:
np.einsum('ij->i',A)  #sum on axis 1

array([ 3,  6, 15])

In [110]:
np.einsum('ij->j',A)  #sum on axis 0

array([8, 8, 8])

In [113]:
np.einsum('ij,ij->ij', A, B) #element-wise multiplication of A and B*

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [115]:
np.einsum('ij,ji->ij', A, B) #element-wise multiplication of A and B.T

array([[0, 1, 1],
       [2, 2, 2],
       [0, 0, 5]])

In [119]:
np.einsum('ij,jk->ik', A, B) #dot(A,B)
# np.einsum('ij,jk', A, B)

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [120]:
np.einsum('ij,jk->ij', A, B) #inner(A,B)  ^?^ what does inner product of 2-D arrays mean?

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 5, 10, 15]])

In [136]:
np.einsum('ij,jk->ijk', A, B) #multiply each row of A with B, shape(i,j,k)

array([[[0, 1, 0],
        [1, 1, 0],
        [1, 1, 1]],

       [[0, 2, 0],
        [2, 2, 0],
        [2, 2, 2]],

       [[0, 5, 0],
        [5, 5, 0],
        [5, 5, 5]]])

In [135]:
np.einsum('ij,kl->ijkl', A, B) #multiply each value of A with B, shape(i,j,k,l)

(3, 3, 3, 3)