## 100 numpy exercises ( www.labri.fr/perso/nrougier/teaching/numpy.100/ )

### 1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print (np.__version__)


1.12.0


In [3]:
np.show_config() #^?^ show_config()?

blas_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
blas_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_mkl_info:
    define_macros = [('SCIPY_MKL_

### 3. Create a null vector of size 10 (★☆☆)

In [303]:
z = np.zeros(10)
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

### 4. How to find the memory size of any array (★☆☆)

In [306]:
Z = np.zeros((10,10))
Z.dtype #float64 occupies 8 bytes

dtype('float64')

In [307]:
Z.itemsize*Z.size

800

### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [317]:
#run `python -c "import numpy; numpy.info(numpy.add)"` #^?^ ERROR: File `'python.py'` not found.

In [318]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


In [308]:
help(np.add) #my solution

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y, ou

In [8]:
z.size

100

In [9]:
z.itemsize

8

In [10]:
print (z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [320]:
Z = np.random.random(10)
Z[4] = 1
Z

array([ 0.46937807,  0.87797773,  0.35506066,  0.57895522,  1.        ,
        0.837703  ,  0.25614186,  0.5963887 ,  0.19736902,  0.0262696 ])

### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [322]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last) (★☆☆)

In [323]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [324]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [329]:
Z = np.nonzero([1,2,0,0,4,0])
Z #tuple type

(array([0, 1, 4]),)

### 11. Create a 3x3 identity matrix (★☆☆)

In [331]:
Z = np.eye(3)
Z

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 12. Create a 3x3x3 array with random values (★☆☆)

In [334]:
Z = np.random.random((3,3,3)) #the shape should be as a tuple (3,3,3)
Z

array([[[ 0.85251296,  0.02040971,  0.02438156],
        [ 0.72825261,  0.1094073 ,  0.08439685],
        [ 0.28189019,  0.39519301,  0.9178116 ]],

       [[ 0.1462066 ,  0.84654966,  0.18785799],
        [ 0.28623353,  0.14123667,  0.62240703],
        [ 0.96865407,  0.19721165,  0.59561673]],

       [[ 0.96695458,  0.93635317,  0.86975932],
        [ 0.77836616,  0.72085438,  0.23568886],
        [ 0.68888303,  0.58919403,  0.74995615]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [337]:
Z = np.random.random((10,10))
Z.max(),Z.min()

(0.99412943675560717, 0.0019059606314421051)

### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [340]:
Z = np.random.random(30)
Z.mean()

0.50614543465060957

### 15.Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [344]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
Z

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [349]:
Z = np.ones((5,5)) 
np.pad(Z,pad_width = 1, mode = 'constant', constant_values = 0) #^*^ numpy.pad: https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

### 17. What is the result of the following expression? (★☆☆)

In [351]:
0 * np.nan

nan

In [352]:
np.nan == np.nan

False

In [354]:
np.inf > np.nan

False

In [355]:
np.nan - np.nan

nan

In [356]:
0.3 == 3 * 0.1

False

In [357]:
#3*0.1

0.30000000000000004

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [362]:
np.diag(np.arange(4), k = 0)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [363]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [368]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [392]:
#My solution
Z = np.random.random((6,7,8))

In [393]:
np.unravel_index(100,Z.shape)

(1, 5, 4)

In [394]:
#My solution
Z.flatten()[100], Z[100//56,100%56//8,(100%56)%8]

(0.22421911767952474, 0.22421911767952474)

### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [395]:
np.array([[0,1],[1,0]])

array([[0, 1],
       [1, 0]])

In [396]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 22. Normalize a 5x5 random matrix (★☆☆)

In [401]:
Z = np.random.random((5,5))
Z

array([[ 0.20936567,  0.31796651,  0.57173178,  0.78588419,  0.31485275],
       [ 0.68863708,  0.08626318,  0.20652899,  0.1169288 ,  0.45021389],
       [ 0.59085111,  0.81157903,  0.07139666,  0.95970017,  0.62780412],
       [ 0.8079448 ,  0.75363945,  0.29656622,  0.24929122,  0.30144745],
       [ 0.92973026,  0.25260032,  0.9942387 ,  0.00145471,  0.75763168]])

In [402]:
Z-Z.min()/Z.max()-Z.min()

array([[ 0.20644782,  0.31504867,  0.56881394,  0.78296634,  0.3119349 ],
       [ 0.68571923,  0.08334533,  0.20361115,  0.11401095,  0.44729604],
       [ 0.58793326,  0.80866118,  0.06847881,  0.95678232,  0.62488627],
       [ 0.80502695,  0.75072161,  0.29364837,  0.24637337,  0.2985296 ],
       [ 0.92681241,  0.24968247,  0.99132085, -0.00146314,  0.75471384]])

### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [418]:
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)]) #^?^ test = np.dtype([("r",np.ubyte,1)?

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [430]:
A = np.random.random((5,3))
B = np.random.random((3,2))

In [431]:
np.dot(A,B) #solution1

array([[ 0.30818588,  0.60489729],
       [ 1.14773158,  1.52282234],
       [ 0.41393972,  0.3950827 ],
       [ 1.1391056 ,  1.20586926],
       [ 1.29999598,  1.63816228]])

In [434]:
A.dot(B) #solution2

array([[ 0.30818588,  0.60489729],
       [ 1.14773158,  1.52282234],
       [ 0.41393972,  0.3950827 ],
       [ 1.1391056 ,  1.20586926],
       [ 1.29999598,  1.63816228]])

In [436]:
A @ B #solution3 for Python3 or above

array([[ 0.30818588,  0.60489729],
       [ 1.14773158,  1.52282234],
       [ 0.41393972,  0.3950827 ],
       [ 1.1391056 ,  1.20586926],
       [ 1.29999598,  1.63816228]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [438]:
Z = np.arange(12)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [443]:
Z[(Z < 8) & (Z > 3)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

### 26. What is the output of the following script? (★☆☆)

In [444]:
sum(range(5),-1) #sum(), sum up, then minus 1

9

In [446]:
np.sum(range(5),-1) #np.sum(), along the last axis

10

### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [449]:
Z = np.random.randint(0,10,10)
Z

array([3, 7, 1, 6, 0, 7, 2, 1, 9, 4])

In [450]:
Z**Z

array([       27,    823543,         1,     46656,         1,    823543,
               4,         1, 387420489,       256])

In [461]:
Z <- Z

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [462]:
1j*Z

array([ 0.+3.j,  0.+7.j,  0.+1.j,  0.+6.j,  0.+0.j,  0.+7.j,  0.+2.j,
        0.+1.j,  0.+9.j,  0.+4.j])

In [451]:
2 << Z >> 2

array([  4,  64,   1,  32,   0,  64,   2,   1, 256,   8])

In [495]:
2<<Z   # ^?^ pow(2,z + 1)?

array([  24,  384,    6,  192,    3,  384,   12,    6, 1536,   48])

In [473]:
Z >> 2 #right shift for 2 bits, with 0s filled in from the left

array([0, 1, 0, 1, 0, 1, 0, 0, 2, 1])

In [ ]:
Z << 2 #left shift for 2 bits, with 0s filled in from the right

In [494]:
-127 >> 2 #2's complement?


-32

In [463]:
Z/1/1

array([ 3.,  7.,  1.,  6.,  0.,  7.,  2.,  1.,  9.,  4.])

In [ ]:
Z <- Z

In [496]:
Z<Z>Z #^?^ the order of concatenation?
(Z<Z)>Z
Z<(Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28. What are the result of the following expressions?

In [506]:
np.array(0) / np.array(0) #^?^ np.array(0)

/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


nan

In [507]:
np.array(0) // np.array(0) 

/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  if __name__ == '__main__':


0

In [508]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

In [509]:
np.array([np.nan]).astype(int).astype(float)

array([ -9.22337204e+18])

### 29. How to round away from zero a float array ? (★☆☆)

In [510]:
Z = np.random.uniform(-10,+10,10)
Z

array([-5.83444393, -5.45501451,  0.16768349,  4.94148358, -5.24809363,
       -0.3253481 ,  1.29319381, -8.21089825,  2.20495641, -1.80475405])

In [515]:
np.ceil(np.abs(Z)), Z

(array([ 6.,  6.,  1.,  5.,  6.,  1.,  2.,  9.,  3.,  2.]),
 array([-5.83444393, -5.45501451,  0.16768349,  4.94148358, -5.24809363,
        -0.3253481 ,  1.29319381, -8.21089825,  2.20495641, -1.80475405]))

In [511]:
np.copysign(np.ceil(np.abs(Z)), Z)

array([-6., -6.,  1.,  5., -6., -1.,  2., -9.,  3., -2.])

### 30. How to find common values between two arrays? (★☆☆)

In [518]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
Z1,Z2

(array([3, 6, 2, 2, 7, 8, 5, 1, 6, 6]), array([2, 8, 5, 1, 8, 4, 5, 5, 3, 6]))

In [519]:
np.intersect1d(Z1,Z2)

array([1, 2, 3, 5, 6, 8])

### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [546]:
defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0  #the warnings supposed to be generated by Numpy becomes ignored now
Z, defaults

(array([ inf]),
 {'divide': 'ignore',
  'invalid': 'ignore',
  'over': 'ignore',
  'under': 'ignore'})

In [542]:
# Back to sanity
_ = np.seterr(**defaults)

In [551]:
#^?^ not working?
#back to sanity
_ = np.seterr(**defaults)
Z = np.ones(1) / 0
Z, _

(array([ inf]),
 {'divide': 'ignore',
  'invalid': 'ignore',
  'over': 'ignore',
  'under': 'ignore'})

In [556]:
#with context manager
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

### 32. Is the following expressions true? (★☆☆)

In [558]:
np.sqrt(-1)

nan

In [559]:
np.emath.sqrt(-1) #with complex number

1j

In [557]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [573]:
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [574]:
yesterday, today, tomorrow

(numpy.datetime64('2017-04-15'),
 numpy.datetime64('2017-04-16'),
 numpy.datetime64('2017-04-17'))

### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [589]:
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]') #datetime64[M] is optional

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

## 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [614]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
A,B,C

(array([ 1.,  1.,  1.]), array([ 2.,  2.,  2.]), array([ 3.,  3.,  3.]))

In [615]:
np.add(A,B,out = B)
A,B,C

(array([ 1.,  1.,  1.]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

In [616]:
np.divide(A,2, out = A)
A,B,C

(array([ 0.5,  0.5,  0.5]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

In [617]:
np.negative(A, out = A)
A,B,C

(array([-0.5, -0.5, -0.5]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

In [618]:
np.multiply(A, B, out = A)
A,B,C

(array([-1.5, -1.5, -1.5]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [620]:
Z = np.random.uniform(0,10,10)
Z

array([ 7.01843308,  4.83948271,  8.18627892,  5.65228203,  8.8623302 ,
        2.82721522,  4.16574847,  8.54583522,  4.12780231,  0.26110065])

In [621]:
Z - Z%1

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

In [624]:
np.floor(Z)

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

In [626]:
np.ceil(Z)-1

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

In [627]:
Z.astype(int)

array([7, 4, 8, 5, 8, 2, 4, 8, 4, 0])

In [628]:
np.trunc(Z)

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [640]:
Z = np.zeros((5,5))
Z += np.arange(5) #propagation
Z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [646]:
def generate():
    for x in range(10):
        yield x

In [653]:
Z = np.fromiter(generate(),dtype=float,count=-1)  #^?^ fromiter(); default count = -1 means all data will be read  #https://docs.scipy.org/doc/numpy/reference/generated/numpy.fromiter.html
Z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [662]:
np.linspace(0,10,12, endpoint= True)[1:-1]

array([ 0.90909091,  1.81818182,  2.72727273,  3.63636364,  4.54545455,
        5.45454545,  6.36363636,  7.27272727,  8.18181818,  9.09090909])

### 40. Create a random vector of size 10 and sort it (★★☆)

In [673]:
Z = np.random.random(10)
Z.sort()

In [674]:
Z

array([ 0.12709871,  0.17264642,  0.24318241,  0.37099115,  0.38227671,
        0.42131952,  0.48331237,  0.5266422 ,  0.88604157,  0.93846475])

### No.50 Subtract the mean of each row of a matrix (★★☆)

In [14]:
Z = np.random.random((10,5))
Z

array([[ 0.93410427,  0.67379227,  0.88338146,  0.44811689,  0.31507984],
       [ 0.19936049,  0.20305681,  0.45024992,  0.08654554,  0.71393222],
       [ 0.98898066,  0.22089623,  0.51181213,  0.9353755 ,  0.1140818 ],
       [ 0.44865318,  0.44437098,  0.21384027,  0.47715187,  0.31609073],
       [ 0.95122818,  0.06468361,  0.46089041,  0.2273167 ,  0.20635827],
       [ 0.19383945,  0.60496262,  0.15516869,  0.20438439,  0.40144749],
       [ 0.16060401,  0.21061711,  0.43886717,  0.30739568,  0.15532012],
       [ 0.36415632,  0.67038416,  0.28938311,  0.59353741,  0.33265015],
       [ 0.33213298,  0.08778509,  0.34516742,  0.65183081,  0.15970114],
       [ 0.286805  ,  0.06390393,  0.25689698,  0.94284406,  0.69304893]])

In [20]:
#solution1
Z - Z.mean(axis = 1, keepdims = True) #horizontal; if keepdims option is false by default, and the operation between (10,5) and (10,) is not broadcastable 
Z

array([[ 0.93410427,  0.67379227,  0.88338146,  0.44811689,  0.31507984],
       [ 0.19936049,  0.20305681,  0.45024992,  0.08654554,  0.71393222],
       [ 0.98898066,  0.22089623,  0.51181213,  0.9353755 ,  0.1140818 ],
       [ 0.44865318,  0.44437098,  0.21384027,  0.47715187,  0.31609073],
       [ 0.95122818,  0.06468361,  0.46089041,  0.2273167 ,  0.20635827],
       [ 0.19383945,  0.60496262,  0.15516869,  0.20438439,  0.40144749],
       [ 0.16060401,  0.21061711,  0.43886717,  0.30739568,  0.15532012],
       [ 0.36415632,  0.67038416,  0.28938311,  0.59353741,  0.33265015],
       [ 0.33213298,  0.08778509,  0.34516742,  0.65183081,  0.15970114],
       [ 0.286805  ,  0.06390393,  0.25689698,  0.94284406,  0.69304893]])

In [21]:
#solution2
Z - Z.mean(axis = 1).reshape(10,1) #horizontal; broadcastable in this way
Z


array([[ 0.93410427,  0.67379227,  0.88338146,  0.44811689,  0.31507984],
       [ 0.19936049,  0.20305681,  0.45024992,  0.08654554,  0.71393222],
       [ 0.98898066,  0.22089623,  0.51181213,  0.9353755 ,  0.1140818 ],
       [ 0.44865318,  0.44437098,  0.21384027,  0.47715187,  0.31609073],
       [ 0.95122818,  0.06468361,  0.46089041,  0.2273167 ,  0.20635827],
       [ 0.19383945,  0.60496262,  0.15516869,  0.20438439,  0.40144749],
       [ 0.16060401,  0.21061711,  0.43886717,  0.30739568,  0.15532012],
       [ 0.36415632,  0.67038416,  0.28938311,  0.59353741,  0.33265015],
       [ 0.33213298,  0.08778509,  0.34516742,  0.65183081,  0.15970114],
       [ 0.286805  ,  0.06390393,  0.25689698,  0.94284406,  0.69304893]])

### No.51 How to I sort an array by the nth column? (★★☆)

In [32]:
Z = np.random.randint(0,10,(3,3))
Z

array([[0, 7, 0],
       [9, 4, 9],
       [6, 2, 6]])

In [33]:
Z[Z[:,1].argsort()]

array([[6, 2, 6],
       [9, 4, 9],
       [0, 7, 0]])

### No.52 How to tell if a given 2D array has null columns? (★★☆)

In [41]:
Z = np.random.randint(0,3,(3,10))
Z

array([[1, 2, 1, 0, 0, 1, 2, 0, 1, 2],
       [1, 0, 0, 1, 0, 1, 0, 1, 0, 1],
       [2, 2, 1, 1, 0, 2, 1, 0, 1, 0]])

In [45]:
(~Z.any(axis=0)).any() ##^*^ numpy.any() https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.any.html

True

### No.53 Find the nearest value from a given value in an array (★★☆)

In [55]:
Z = np.random.uniform(0,1,10)
z = 0.5 # 0.5 is the given value
Z

array([ 0.8019924 ,  0.55812004,  0.98339659,  0.05513788,  0.48069263,
        0.16687099,  0.8343183 ,  0.16984431,  0.61935177,  0.87900648])

In [56]:
Z.flat #flatiter object
# Z.flatten()

In [57]:
m = Z.flat[np.abs(Z - z).argmin()]
m

0.48069263400602491

### No.54 Create an array class that has a name attribute (★★☆)

In [72]:
Z.view()

NamedArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# ^*^ https://docs.python.org/3/tutorial/classes.html
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


### No.55 Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [96]:
#I.append([1]) #^?^ how to append a new element to np.ndarray

In [98]:
np.bincount(I, minlength=15)

array([3, 4, 2, 2, 0, 1, 4, 1, 0, 3, 0, 0, 0, 0, 0])

In [87]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z)) #  is minlength is optional
Z

array([ 4.,  5.,  3.,  3.,  1.,  2.,  5.,  2.,  1.,  4.])

### No.56 How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [105]:
# ^?^ what does the question mean?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [103]:
np.bincount(X)

array([0, 1, 1, 1, 1, 1, 1])

### No.57 Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [235]:
h,w = 16,16

In [236]:
I = np.random.randint(0,16,(h,w,3)).astype(np.ubyte)
I

array([[[ 4, 15,  3],
        [ 4,  8, 15],
        [15,  3,  1],
        [ 4,  5,  1],
        [ 0,  1,  6],
        [ 7, 13,  8],
        [ 5, 10, 11],
        [14,  0,  1],
        [ 1, 12, 14],
        [13,  7,  4],
        [ 4,  5,  7],
        [10,  2, 15],
        [15,  7, 12],
        [ 1, 14, 11],
        [ 4, 15,  9],
        [ 4,  9, 14]],

       [[12,  7,  0],
        [ 8, 12,  5],
        [ 2,  3,  2],
        [12, 12,  2],
        [ 3,  4, 13],
        [ 6,  4,  4],
        [ 6,  9,  1],
        [ 6, 11, 14],
        [ 2,  0,  2],
        [ 9,  0, 12],
        [15,  9,  4],
        [15, 10, 15],
        [ 1,  1,  2],
        [10,  0,  1],
        [ 4, 10,  2],
        [ 5,  2,  4]],

       [[ 5,  2,  7],
        [ 5, 13,  0],
        [ 3,  7,  9],
        [15, 14,  6],
        [ 1, 13,  2],
        [14,  4, 10],
        [ 4, 13, 14],
        [ 6,  1,  8],
        [13,  5,  1],
        [13,  1,  0],
        [10, 15,  5],
        [ 0, 12,  9],
        [ 6, 15, 11],
      

In [237]:
F = I[...,0]*64+I[...,1]*16 + I[...,0] #^?^ when * 256 * 256 rather than * 65536, the result of the first item will be 0
U = np.unique(F)
Z = len(U)
Z

152

### No. 58 Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [278]:
A = np.random.randint(0,10,(3,4,3,4))
A

array([[[[5, 0, 4, 6],
         [1, 6, 8, 1],
         [9, 4, 9, 9]],

        [[4, 6, 9, 5],
         [7, 9, 2, 3],
         [8, 6, 3, 6]],

        [[0, 0, 2, 2],
         [5, 8, 7, 8],
         [9, 9, 3, 9]],

        [[2, 8, 0, 1],
         [3, 5, 4, 0],
         [5, 9, 8, 7]]],


       [[[1, 1, 4, 0],
         [3, 9, 7, 5],
         [9, 0, 0, 8]],

        [[2, 8, 4, 0],
         [8, 1, 7, 5],
         [5, 9, 4, 5]],

        [[6, 6, 0, 5],
         [0, 8, 8, 5],
         [2, 8, 7, 1]],

        [[6, 5, 5, 0],
         [6, 0, 8, 3],
         [8, 5, 0, 6]]],


       [[[5, 3, 0, 7],
         [0, 4, 4, 6],
         [6, 6, 3, 3]],

        [[6, 8, 0, 3],
         [3, 8, 7, 3],
         [6, 6, 6, 8]],

        [[5, 3, 5, 3],
         [1, 6, 3, 5],
         [7, 6, 2, 1]],

        [[6, 6, 3, 2],
         [5, 0, 6, 9],
         [5, 0, 6, 5]]]])

In [293]:
A.reshape(A.shape[:-2]+(-1,)).sum(axis=-1) # along the last axis

array([[62, 68, 62, 52],
       [47, 58, 56, 52],
       [47, 64, 47, 53]])

In [289]:
# A[...,:,:].flatten() #^?^ flatten() not to the dimensions?

array([5, 0, 4, 6, 1, 6, 8, 1, 9, 4, 9, 9, 4, 6, 9, 5, 7, 9, 2, 3, 8, 6, 3,
       6, 0, 0, 2, 2, 5, 8, 7, 8, 9, 9, 3, 9, 2, 8, 0, 1, 3, 5, 4, 0, 5, 9,
       8, 7, 1, 1, 4, 0, 3, 9, 7, 5, 9, 0, 0, 8, 2, 8, 4, 0, 8, 1, 7, 5, 5,
       9, 4, 5, 6, 6, 0, 5, 0, 8, 8, 5, 2, 8, 7, 1, 6, 5, 5, 0, 6, 0, 8, 3,
       8, 5, 0, 6, 5, 3, 0, 7, 0, 4, 4, 6, 6, 6, 3, 3, 6, 8, 0, 3, 3, 8, 7,
       3, 6, 6, 6, 8, 5, 3, 5, 3, 1, 6, 3, 5, 7, 6, 2, 1, 6, 6, 3, 2, 5, 0,
       6, 9, 5, 0, 6, 5])

### No.59 Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [677]:
np.array([6.] * 5)

array([ 6.,  6.,  6.,  6.,  6.])

In [680]:
np.array([10.] * 18).reshape(2,3,3)



array([[[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]],

       [[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]]])