# 100 numpy exercises 
( http://www.labri.fr/perso/nrougier/teaching/numpy.100/ )  
(https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises.md)

### 1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print (np.__version__)


1.12.0


In [3]:
np.show_config() #^?^ show_config()?

blas_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
blas_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_mkl_info:
    define_macros = [('SCIPY_MKL_

### 3. Create a null vector of size 10 (★☆☆)

In [303]:
z = np.zeros(10)
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

### 4. How to find the memory size of any array (★☆☆)

In [306]:
Z = np.zeros((10,10))
Z.dtype #float64 occupies 8 bytes

dtype('float64')

In [307]:
Z.itemsize*Z.size

800

### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [317]:
#run `python -c "import numpy; numpy.info(numpy.add)"` #^?^ ERROR: File `'python.py'` not found.

In [318]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


In [308]:
help(np.add) #my solution

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y, ou

In [8]:
z.size

100

In [9]:
z.itemsize

8

In [10]:
print (z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [320]:
Z = np.random.random(10)
Z[4] = 1
Z

array([ 0.46937807,  0.87797773,  0.35506066,  0.57895522,  1.        ,
        0.837703  ,  0.25614186,  0.5963887 ,  0.19736902,  0.0262696 ])

### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [322]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last) (★☆☆)

In [323]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [324]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [329]:
Z = np.nonzero([1,2,0,0,4,0])
Z #tuple type

(array([0, 1, 4]),)

### 11. Create a 3x3 identity matrix (★☆☆)

In [331]:
Z = np.eye(3)
Z

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 12. Create a 3x3x3 array with random values (★☆☆)

In [334]:
Z = np.random.random((3,3,3)) #the shape should be as a tuple (3,3,3)
Z

array([[[ 0.85251296,  0.02040971,  0.02438156],
        [ 0.72825261,  0.1094073 ,  0.08439685],
        [ 0.28189019,  0.39519301,  0.9178116 ]],

       [[ 0.1462066 ,  0.84654966,  0.18785799],
        [ 0.28623353,  0.14123667,  0.62240703],
        [ 0.96865407,  0.19721165,  0.59561673]],

       [[ 0.96695458,  0.93635317,  0.86975932],
        [ 0.77836616,  0.72085438,  0.23568886],
        [ 0.68888303,  0.58919403,  0.74995615]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [337]:
Z = np.random.random((10,10))
Z.max(),Z.min()

(0.99412943675560717, 0.0019059606314421051)

### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [340]:
Z = np.random.random(30)
Z.mean()

0.50614543465060957

### 15.Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [344]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
Z

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [349]:
Z = np.ones((5,5)) 
np.pad(Z,pad_width = 1, mode = 'constant', constant_values = 0) #^*^ numpy.pad: https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

### 17. What is the result of the following expression? (★☆☆)

In [351]:
0 * np.nan

nan

In [352]:
np.nan == np.nan

False

In [354]:
np.inf > np.nan

False

In [355]:
np.nan - np.nan

nan

In [356]:
0.3 == 3 * 0.1

False

In [357]:
#3*0.1

0.30000000000000004

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [362]:
np.diag(np.arange(4), k = 0)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [363]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [368]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [392]:
#My solution
Z = np.random.random((6,7,8))

In [393]:
np.unravel_index(100,Z.shape)

(1, 5, 4)

In [394]:
#My solution
Z.flatten()[100], Z[100//56,100%56//8,(100%56)%8]

(0.22421911767952474, 0.22421911767952474)

### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [395]:
np.array([[0,1],[1,0]])

array([[0, 1],
       [1, 0]])

In [396]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 22. Normalize a 5x5 random matrix (★☆☆)

In [401]:
Z = np.random.random((5,5))
Z

array([[ 0.20936567,  0.31796651,  0.57173178,  0.78588419,  0.31485275],
       [ 0.68863708,  0.08626318,  0.20652899,  0.1169288 ,  0.45021389],
       [ 0.59085111,  0.81157903,  0.07139666,  0.95970017,  0.62780412],
       [ 0.8079448 ,  0.75363945,  0.29656622,  0.24929122,  0.30144745],
       [ 0.92973026,  0.25260032,  0.9942387 ,  0.00145471,  0.75763168]])

In [402]:
Z-Z.min()/Z.max()-Z.min()

array([[ 0.20644782,  0.31504867,  0.56881394,  0.78296634,  0.3119349 ],
       [ 0.68571923,  0.08334533,  0.20361115,  0.11401095,  0.44729604],
       [ 0.58793326,  0.80866118,  0.06847881,  0.95678232,  0.62488627],
       [ 0.80502695,  0.75072161,  0.29364837,  0.24637337,  0.2985296 ],
       [ 0.92681241,  0.24968247,  0.99132085, -0.00146314,  0.75471384]])

### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [418]:
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)]) #^?^ test = np.dtype([("r",np.ubyte,1)?

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [430]:
A = np.random.random((5,3))
B = np.random.random((3,2))

In [431]:
np.dot(A,B) #solution1

array([[ 0.30818588,  0.60489729],
       [ 1.14773158,  1.52282234],
       [ 0.41393972,  0.3950827 ],
       [ 1.1391056 ,  1.20586926],
       [ 1.29999598,  1.63816228]])

In [434]:
A.dot(B) #solution2

array([[ 0.30818588,  0.60489729],
       [ 1.14773158,  1.52282234],
       [ 0.41393972,  0.3950827 ],
       [ 1.1391056 ,  1.20586926],
       [ 1.29999598,  1.63816228]])

In [436]:
A @ B #solution3 for Python3 or above

array([[ 0.30818588,  0.60489729],
       [ 1.14773158,  1.52282234],
       [ 0.41393972,  0.3950827 ],
       [ 1.1391056 ,  1.20586926],
       [ 1.29999598,  1.63816228]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [438]:
Z = np.arange(12)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [443]:
Z[(Z < 8) & (Z > 3)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

### 26. What is the output of the following script? (★☆☆)

In [444]:
sum(range(5),-1) #sum(), sum up, then minus 1

9

In [446]:
np.sum(range(5),-1) #np.sum(), along the last axis

10

### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [449]:
Z = np.random.randint(0,10,10)
Z

array([3, 7, 1, 6, 0, 7, 2, 1, 9, 4])

In [450]:
Z**Z

array([       27,    823543,         1,     46656,         1,    823543,
               4,         1, 387420489,       256])

In [461]:
Z <- Z

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [462]:
1j*Z

array([ 0.+3.j,  0.+7.j,  0.+1.j,  0.+6.j,  0.+0.j,  0.+7.j,  0.+2.j,
        0.+1.j,  0.+9.j,  0.+4.j])

In [451]:
2 << Z >> 2

array([  4,  64,   1,  32,   0,  64,   2,   1, 256,   8])

In [495]:
2<<Z   # ^?^ pow(2,z + 1)?

array([  24,  384,    6,  192,    3,  384,   12,    6, 1536,   48])

In [473]:
Z >> 2 #right shift for 2 bits, with 0s filled in from the left

array([0, 1, 0, 1, 0, 1, 0, 0, 2, 1])

In [ ]:
Z << 2 #left shift for 2 bits, with 0s filled in from the right

In [494]:
-127 >> 2 #2's complement?


-32

In [463]:
Z/1/1

array([ 3.,  7.,  1.,  6.,  0.,  7.,  2.,  1.,  9.,  4.])

In [ ]:
Z <- Z

In [496]:
Z<Z>Z #^?^ the order of concatenation?
(Z<Z)>Z
Z<(Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28. What are the result of the following expressions?

In [506]:
np.array(0) / np.array(0) #^?^ np.array(0)

/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


nan

In [507]:
np.array(0) // np.array(0) 

/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  if __name__ == '__main__':


0

In [508]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

In [509]:
np.array([np.nan]).astype(int).astype(float)

array([ -9.22337204e+18])

### 29. How to round away from zero a float array ? (★☆☆)

In [510]:
Z = np.random.uniform(-10,+10,10)
Z

array([-5.83444393, -5.45501451,  0.16768349,  4.94148358, -5.24809363,
       -0.3253481 ,  1.29319381, -8.21089825,  2.20495641, -1.80475405])

In [515]:
np.ceil(np.abs(Z)), Z

(array([ 6.,  6.,  1.,  5.,  6.,  1.,  2.,  9.,  3.,  2.]),
 array([-5.83444393, -5.45501451,  0.16768349,  4.94148358, -5.24809363,
        -0.3253481 ,  1.29319381, -8.21089825,  2.20495641, -1.80475405]))

In [511]:
np.copysign(np.ceil(np.abs(Z)), Z)

array([-6., -6.,  1.,  5., -6., -1.,  2., -9.,  3., -2.])

### 30. How to find common values between two arrays? (★☆☆)

In [518]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
Z1,Z2

(array([3, 6, 2, 2, 7, 8, 5, 1, 6, 6]), array([2, 8, 5, 1, 8, 4, 5, 5, 3, 6]))

In [519]:
np.intersect1d(Z1,Z2)

array([1, 2, 3, 5, 6, 8])

### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [546]:
defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0  #the warnings supposed to be generated by Numpy becomes ignored now
Z, defaults

(array([ inf]),
 {'divide': 'ignore',
  'invalid': 'ignore',
  'over': 'ignore',
  'under': 'ignore'})

In [542]:
# Back to sanity
_ = np.seterr(**defaults)

In [551]:
#^?^ not working?
#back to sanity
_ = np.seterr(**defaults)
Z = np.ones(1) / 0
Z, _

(array([ inf]),
 {'divide': 'ignore',
  'invalid': 'ignore',
  'over': 'ignore',
  'under': 'ignore'})

In [556]:
#with context manager
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

### 32. Is the following expressions true? (★☆☆)

In [558]:
np.sqrt(-1)

nan

In [559]:
np.emath.sqrt(-1) #with complex number

1j

In [557]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [573]:
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [574]:
yesterday, today, tomorrow

(numpy.datetime64('2017-04-15'),
 numpy.datetime64('2017-04-16'),
 numpy.datetime64('2017-04-17'))

### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [589]:
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]') #datetime64[M] is optional

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

## 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [614]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
A,B,C

(array([ 1.,  1.,  1.]), array([ 2.,  2.,  2.]), array([ 3.,  3.,  3.]))

In [615]:
np.add(A,B,out = B)
A,B,C

(array([ 1.,  1.,  1.]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

In [616]:
np.divide(A,2, out = A)
A,B,C

(array([ 0.5,  0.5,  0.5]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

In [617]:
np.negative(A, out = A)
A,B,C

(array([-0.5, -0.5, -0.5]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

In [618]:
np.multiply(A, B, out = A)
A,B,C

(array([-1.5, -1.5, -1.5]), array([ 3.,  3.,  3.]), array([ 3.,  3.,  3.]))

### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [620]:
Z = np.random.uniform(0,10,10)
Z

array([ 7.01843308,  4.83948271,  8.18627892,  5.65228203,  8.8623302 ,
        2.82721522,  4.16574847,  8.54583522,  4.12780231,  0.26110065])

In [621]:
Z - Z%1

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

In [624]:
np.floor(Z)

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

In [626]:
np.ceil(Z)-1

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

In [627]:
Z.astype(int)

array([7, 4, 8, 5, 8, 2, 4, 8, 4, 0])

In [628]:
np.trunc(Z)

array([ 7.,  4.,  8.,  5.,  8.,  2.,  4.,  8.,  4.,  0.])

### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [640]:
Z = np.zeros((5,5))
Z += np.arange(5) #propagation
Z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [646]:
def generate():
    for x in range(10):
        yield x

In [653]:
Z = np.fromiter(generate(),dtype=float,count=-1)  #^?^ fromiter(); default count = -1 means all data will be read  #https://docs.scipy.org/doc/numpy/reference/generated/numpy.fromiter.html
Z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [662]:
np.linspace(0,10,12, endpoint= True)[1:-1]

array([ 0.90909091,  1.81818182,  2.72727273,  3.63636364,  4.54545455,
        5.45454545,  6.36363636,  7.27272727,  8.18181818,  9.09090909])

### 40. Create a random vector of size 10 and sort it (★★☆)

In [3]:
Z = np.random.random(10)
Z.sort()

In [4]:
Z

array([ 0.00574671,  0.2977225 ,  0.44216926,  0.56832259,  0.57400374,
        0.62029067,  0.78693547,  0.78993535,  0.822849  ,  0.8337766 ])

### 41. How to sum a small array faster than np.sum? (★★☆)

In [22]:
Z = np.random.random(10)
Z

array([ 0.26055286,  0.86102059,  0.7632628 ,  0.98787986,  0.58561718,
        0.17761368,  0.68964756,  0.39639237,  0.33902173,  0.80209473])

In [24]:
%timeit np.sum(Z)

The slowest run took 9.78 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.24 µs per loop


In [25]:
%timeit np.add.reduce(Z)

The slowest run took 19.18 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.33 µs per loop


^?^ why add.reduce is faster?

### 42. Consider two random array A and B, check if they are equal (★★☆)

In [48]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print (A,B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B) #^?^ allclose?
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 1 1 0 0] [1 0 1 1 0]
False
False


### 43. Make an array immutable (read-only) (★★☆)

In [49]:
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [50]:
Z.flags.writeable = False

In [51]:
Z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False

In [54]:
Z[0] = 1 #read-only

ValueError: assignment destination is read-only

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [56]:
Z = np.random.random((10,2))
Z

array([[ 0.8231246 ,  0.0945745 ],
       [ 0.06927747,  0.56994457],
       [ 0.42431978,  0.54424658],
       [ 0.93880001,  0.25668879],
       [ 0.00956234,  0.845604  ],
       [ 0.16238074,  0.07672982],
       [ 0.54722871,  0.77376274],
       [ 0.54929705,  0.90531682],
       [ 0.56815124,  0.09128723],
       [ 0.70787372,  0.7128303 ]])

In [68]:
X = Z[:,0]
Y = Z[:,1]

In [83]:
R = np.sqrt(X**2 + Y**2)
TH = np.arctan2(Y,X) #^?^ arctan2

In [85]:
print (R,TH)

[ 0.82853995  0.57413951  0.69010986  0.97325978  0.84565807  0.17959669
  0.94771727  1.05892672  0.57543825  1.00459556] [ 0.11439532  1.44983847  0.90859004  0.26689878  1.55948852  0.44143138
  0.95523406  1.02543154  0.15931254  0.78888697]


### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [89]:
Z = np.random.random(10)
Z

array([ 0.03335648,  0.7403817 ,  0.92640715,  0.56528033,  0.08828252,
        0.07221941,  0.47051614,  0.7091285 ,  0.50095591,  0.47181983])

In [90]:
Z[Z.argmax()] = 0
Z

array([ 0.03335648,  0.7403817 ,  0.        ,  0.56528033,  0.08828252,
        0.07221941,  0.47051614,  0.7091285 ,  0.50095591,  0.47181983])

### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [126]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

In [127]:
m = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

In [129]:
print(Z) #^?^ how to output in a certain format

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [137]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y) #https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.outer.html

C

In [139]:
print(np.linalg.det(C))

3638.16363712


### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [149]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype))
#    print(np.iinfo(dtype).min)
#    print(np.iinfo(dtype).max)

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [153]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype))
#    print(np.finfo(dtype).min)
#    print(np.finfo(dtype).max)
#    print(np.finfo(dtype).eps)  #^?^ what is eps?

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



### 49. How to print all the values of an array? (★★☆)

In [180]:
np.set_printoptions(threshold=5)  #^?^ https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html
Z = np.random.random((16,16))
print(Z)

[[ 0.13976509  0.80629573  0.8675884  ...,  0.59720471  0.23986353
   0.99802276]
 [ 0.62846794  0.36930092  0.21257882 ...,  0.35805292  0.46042803
   0.1307832 ]
 [ 0.46902815  0.05752314  0.17436754 ...,  0.37818637  0.68256145
   0.84252132]
 ..., 
 [ 0.89133869  0.56009113  0.29949115 ...,  0.94170903  0.81213262
   0.02649304]
 [ 0.22769615  0.39433683  0.99220753 ...,  0.89645826  0.32778343
   0.56514695]
 [ 0.74576096  0.08461795  0.705803   ...,  0.35139903  0.78202111
   0.66057269]]


In [181]:
np.set_printoptions(threshold=np.nan)
print(Z)

[[ 0.13976509  0.80629573  0.8675884   0.45811506  0.80169783  0.2188205
   0.55025006  0.76526472  0.69993527  0.54135354  0.84304892  0.19731636
   0.03768601  0.59720471  0.23986353  0.99802276]
 [ 0.62846794  0.36930092  0.21257882  0.96355138  0.49972051  0.3564305
   0.70363004  0.49237203  0.05805038  0.44829256  0.60973719  0.02526343
   0.15867396  0.35805292  0.46042803  0.1307832 ]
 [ 0.46902815  0.05752314  0.17436754  0.34677052  0.51564847  0.20318069
   0.04071276  0.36997317  0.65023385  0.00580055  0.01300148  0.21747419
   0.98594877  0.37818637  0.68256145  0.84252132]
 [ 0.68988114  0.9347479   0.09999228  0.35065201  0.75495355  0.44704488
   0.07518489  0.38801482  0.05622536  0.61518365  0.809372    0.76388841
   0.77229913  0.14764717  0.5443776   0.10039076]
 [ 0.24268979  0.41235056  0.9104172   0.48739652  0.67414643  0.2860625
   0.00647316  0.70218918  0.43822332  0.83493063  0.89548406  0.35893928
   0.82952754  0.01072823  0.71477371  0.71523669]
 [ 0.980

### No.50 Subtract the mean of each row of a matrix (★★☆)

In [14]:
Z = np.random.random((10,5))
Z

array([[ 0.93410427,  0.67379227,  0.88338146,  0.44811689,  0.31507984],
       [ 0.19936049,  0.20305681,  0.45024992,  0.08654554,  0.71393222],
       [ 0.98898066,  0.22089623,  0.51181213,  0.9353755 ,  0.1140818 ],
       [ 0.44865318,  0.44437098,  0.21384027,  0.47715187,  0.31609073],
       [ 0.95122818,  0.06468361,  0.46089041,  0.2273167 ,  0.20635827],
       [ 0.19383945,  0.60496262,  0.15516869,  0.20438439,  0.40144749],
       [ 0.16060401,  0.21061711,  0.43886717,  0.30739568,  0.15532012],
       [ 0.36415632,  0.67038416,  0.28938311,  0.59353741,  0.33265015],
       [ 0.33213298,  0.08778509,  0.34516742,  0.65183081,  0.15970114],
       [ 0.286805  ,  0.06390393,  0.25689698,  0.94284406,  0.69304893]])

In [20]:
#solution1
Z - Z.mean(axis = 1, keepdims = True) #horizontal; if keepdims option is false by default, and the operation between (10,5) and (10,) is not broadcastable 
Z

array([[ 0.93410427,  0.67379227,  0.88338146,  0.44811689,  0.31507984],
       [ 0.19936049,  0.20305681,  0.45024992,  0.08654554,  0.71393222],
       [ 0.98898066,  0.22089623,  0.51181213,  0.9353755 ,  0.1140818 ],
       [ 0.44865318,  0.44437098,  0.21384027,  0.47715187,  0.31609073],
       [ 0.95122818,  0.06468361,  0.46089041,  0.2273167 ,  0.20635827],
       [ 0.19383945,  0.60496262,  0.15516869,  0.20438439,  0.40144749],
       [ 0.16060401,  0.21061711,  0.43886717,  0.30739568,  0.15532012],
       [ 0.36415632,  0.67038416,  0.28938311,  0.59353741,  0.33265015],
       [ 0.33213298,  0.08778509,  0.34516742,  0.65183081,  0.15970114],
       [ 0.286805  ,  0.06390393,  0.25689698,  0.94284406,  0.69304893]])

In [21]:
#solution2
Z - Z.mean(axis = 1).reshape(10,1) #horizontal; broadcastable in this way
Z


array([[ 0.93410427,  0.67379227,  0.88338146,  0.44811689,  0.31507984],
       [ 0.19936049,  0.20305681,  0.45024992,  0.08654554,  0.71393222],
       [ 0.98898066,  0.22089623,  0.51181213,  0.9353755 ,  0.1140818 ],
       [ 0.44865318,  0.44437098,  0.21384027,  0.47715187,  0.31609073],
       [ 0.95122818,  0.06468361,  0.46089041,  0.2273167 ,  0.20635827],
       [ 0.19383945,  0.60496262,  0.15516869,  0.20438439,  0.40144749],
       [ 0.16060401,  0.21061711,  0.43886717,  0.30739568,  0.15532012],
       [ 0.36415632,  0.67038416,  0.28938311,  0.59353741,  0.33265015],
       [ 0.33213298,  0.08778509,  0.34516742,  0.65183081,  0.15970114],
       [ 0.286805  ,  0.06390393,  0.25689698,  0.94284406,  0.69304893]])

### No.51 How to I sort an array by the nth column? (★★☆)

In [32]:
Z = np.random.randint(0,10,(3,3))
Z

array([[0, 7, 0],
       [9, 4, 9],
       [6, 2, 6]])

In [33]:
Z[Z[:,1].argsort()]

array([[6, 2, 6],
       [9, 4, 9],
       [0, 7, 0]])

### No.52 How to tell if a given 2D array has null columns? (★★☆)

In [41]:
Z = np.random.randint(0,3,(3,10))
Z

array([[1, 2, 1, 0, 0, 1, 2, 0, 1, 2],
       [1, 0, 0, 1, 0, 1, 0, 1, 0, 1],
       [2, 2, 1, 1, 0, 2, 1, 0, 1, 0]])

In [45]:
(~Z.any(axis=0)).any() ##^*^ numpy.any() https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.any.html

True

### No.53 Find the nearest value from a given value in an array (★★☆)

In [55]:
Z = np.random.uniform(0,1,10)
z = 0.5 # 0.5 is the given value
Z

array([ 0.8019924 ,  0.55812004,  0.98339659,  0.05513788,  0.48069263,
        0.16687099,  0.8343183 ,  0.16984431,  0.61935177,  0.87900648])

In [56]:
Z.flat #flatiter object
# Z.flatten()

In [57]:
m = Z.flat[np.abs(Z - z).argmin()]
m

0.48069263400602491

### No.54 How to read the following file? (★★☆)

In [298]:
from io import StringIO  #^?^ error

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

TypeError: Can't convert 'bytes' object to str implicitly

### No.55 What is the equivalent of enumerate for numpy arrays? (★★☆)

In [296]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### No.56 Generate a generic 2D Gaussian-like array (★★☆)

In [295]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

In [103]:
np.bincount(X)

array([0, 1, 1, 1, 1, 1, 1])

### No.57 How to randomly place p elements in a 2D array? (★★☆)

In [294]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1) #^?^ replace?
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### No. 58 Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [278]:
A = np.random.randint(0,10,(3,4,3,4))
A

array([[[[5, 0, 4, 6],
         [1, 6, 8, 1],
         [9, 4, 9, 9]],

        [[4, 6, 9, 5],
         [7, 9, 2, 3],
         [8, 6, 3, 6]],

        [[0, 0, 2, 2],
         [5, 8, 7, 8],
         [9, 9, 3, 9]],

        [[2, 8, 0, 1],
         [3, 5, 4, 0],
         [5, 9, 8, 7]]],


       [[[1, 1, 4, 0],
         [3, 9, 7, 5],
         [9, 0, 0, 8]],

        [[2, 8, 4, 0],
         [8, 1, 7, 5],
         [5, 9, 4, 5]],

        [[6, 6, 0, 5],
         [0, 8, 8, 5],
         [2, 8, 7, 1]],

        [[6, 5, 5, 0],
         [6, 0, 8, 3],
         [8, 5, 0, 6]]],


       [[[5, 3, 0, 7],
         [0, 4, 4, 6],
         [6, 6, 3, 3]],

        [[6, 8, 0, 3],
         [3, 8, 7, 3],
         [6, 6, 6, 8]],

        [[5, 3, 5, 3],
         [1, 6, 3, 5],
         [7, 6, 2, 1]],

        [[6, 6, 3, 2],
         [5, 0, 6, 9],
         [5, 0, 6, 5]]]])

In [293]:
A.reshape(A.shape[:-2]+(-1,)).sum(axis=-1) # along the last axis

array([[62, 68, 62, 52],
       [47, 58, 56, 52],
       [47, 64, 47, 53]])

In [289]:
# A[...,:,:].flatten() #^?^ flatten() not to the dimensions?

array([5, 0, 4, 6, 1, 6, 8, 1, 9, 4, 9, 9, 4, 6, 9, 5, 7, 9, 2, 3, 8, 6, 3,
       6, 0, 0, 2, 2, 5, 8, 7, 8, 9, 9, 3, 9, 2, 8, 0, 1, 3, 5, 4, 0, 5, 9,
       8, 7, 1, 1, 4, 0, 3, 9, 7, 5, 9, 0, 0, 8, 2, 8, 4, 0, 8, 1, 7, 5, 5,
       9, 4, 5, 6, 6, 0, 5, 0, 8, 8, 5, 2, 8, 7, 1, 6, 5, 5, 0, 6, 0, 8, 3,
       8, 5, 0, 6, 5, 3, 0, 7, 0, 4, 4, 6, 6, 6, 3, 3, 6, 8, 0, 3, 3, 8, 7,
       3, 6, 6, 6, 8, 5, 3, 5, 3, 1, 6, 3, 5, 7, 6, 2, 1, 6, 6, 3, 2, 5, 0,
       6, 9, 5, 0, 6, 5])

### No.59 Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [677]:
np.array([6.] * 5)

array([ 6.,  6.,  6.,  6.,  6.])

In [680]:
np.array([10.] * 18).reshape(2,3,3)

array([[[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]],

       [[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]]])

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame({'a': np.random.randn(1000),
   ...:                    'b': np.random.randn(1000),
   ...:                    'N': np.random.randint(100, 1000, (1000)),
   ...:                    'x': 'x'})

In [16]:
def integrate_f(a, b, N):
   ...:     s = 0
   ...:     dx = (b - a) / N
   ...:     for i in range(N):
   ...:         s += f(a + i * dx)
   ...:     return s * dx

In [17]:
def f(x):
    return x * (x - 1)

In [18]:
df

N         a         b  x
0    251  0.855938 -0.994102  x
1    414 -1.804554 -1.346053  x
2    968 -0.615014 -0.410384  x
3    841 -0.556019  0.608098  x
4    639  1.104986  0.014131  x
5    788 -0.370710  0.458011  x
6    983  0.205533  0.229954  x
7    533 -2.926312 -0.774470  x
8    512  0.357283  0.863064  x
9    124  0.506845 -0.476182  x
10   832  0.345342 -0.568040  x
11   470  0.012265  0.780442  x
12   496  0.687346 -2.177448  x
13   343  0.338872  1.388983  x
14   731 -0.921239 -0.713156  x
15   208  1.277183  0.927853  x
16   363  1.571415 -1.714906  x
17   959 -0.199652  0.087787  x
18   290 -1.310707  0.244680  x
19   816  0.375009 -2.003942  x
20   533 -0.911928 -1.347935  x
21   183 -0.248216  1.004602  x
22   758  0.645590  1.810299  x
23   955 -0.409599  0.154435  x
24   782 -1.459414  0.468577  x
25   470  0.691808  1.230878  x
26   740 -0.228604 -1.258319  x
27   245  0.558469  1.054836  x
28   797 -0.209676 -0.014100  x
29   472 -2.057101  1.878013  x
..   ...       ...       ... ..
970  808  0.779964 -0.124913  x
971  793 -0.643805 -0.168194  x
972  490 -0.325242  1.109643  x
973  330  1.246461  0.652542  x
974  607  0.099461  0.135997  x
975  499 -0.267776  0.706981  x
976  504 -0.743216 -0.594847  x
977  992  1.279886 -0.414287  x
978  103 -0.613952  0.232074  x
979  357 -0.166164 -1.324177  x
980  116 -0.370105  1.791594  x
981  756 -0.267656 -0.841408  x
982  802 -1.281904  0.419593  x
983  648 -0.861712  0.216275  x
984  486 -0.377078 -0.809595  x
985  833  1.212637 -0.635043  x
986  444  2.017657  0.067350  x
987  339  0.259370 -0.055195  x
988  650  0.800518 -0.317844  x
989  582 -1.404004 -0.634023  x
990  323  0.549177  1.370143  x
991  926 -0.706211  1.047690  x
992  571 -0.040528 -0.855624  x
993  678 -0.763372  0.243061  x
994  610  1.341204 -1.411305  x
995  856  0.163336 -0.090342  x
996  518  0.202139 -0.238708  x
997  984  2.519607  2.723128  x
998  650  0.552118  0.037637  x
999  789 -0.933492  0.571256  x

[1000 rows x 4 columns]

In [19]:
%timeit df.apply(lambda x: integrate_f(x['a'], x['b'], x['N']), axis=1)

1 loop, best of 3: 202 ms per loop


### 60. How to tell if a given 2D array has null columns? (★★☆)

In [216]:
#null column here means columns containing only zeros
Z = np.random.randint(0,3,(3,10))    #^?^ how to keep generating the matrices until there is a qualified one 
Z

array([[2, 1, 1, 0, 2, 0, 1, 1, 0, 2],
       [1, 2, 2, 1, 0, 0, 0, 0, 2, 0],
       [0, 2, 1, 2, 0, 1, 1, 2, 0, 1]])

In [218]:
~Z.any(axis=0).any() #if it is an all-false array.any(), the result will be true

False

### 61. Find the nearest value from a given value in an array (★★☆)

In [236]:
Z = np.random.uniform(0,1,(10,10))
Z

array([[ 0.96018128,  0.46230226,  0.81921745,  0.30967039,  0.62805375,
         0.57822917,  0.73987094,  0.44575813,  0.37605395,  0.17355742],
       [ 0.14278598,  0.46256143,  0.27708001,  0.9993967 ,  0.10691537,
         0.53908606,  0.34039314,  0.95393346,  0.87948972,  0.46977036],
       [ 0.7176702 ,  0.07396756,  0.81702103,  0.86637122,  0.00271048,
         0.81025683,  0.25003138,  0.98014792,  0.85094206,  0.22856153],
       [ 0.03074925,  0.88283968,  0.79390079,  0.14816034,  0.59246331,
         0.14947036,  0.71832501,  0.44393326,  0.3780032 ,  0.18082757],
       [ 0.65130131,  0.34185623,  0.3886104 ,  0.37769426,  0.61421525,
         0.29924037,  0.06786067,  0.60960345,  0.10264906,  0.92645535],
       [ 0.46340051,  0.73820129,  0.63105872,  0.48193741,  0.94713334,
         0.270412  ,  0.62624969,  0.71292625,  0.0808804 ,  0.49330947],
       [ 0.31296943,  0.68883089,  0.39804639,  0.96077087,  0.35426713,
         0.05586865,  0.01410505,  0.97518865

In [237]:
z = 0.5

In [238]:
iMin = np.abs(Z - z).argmin()
iMin, Z.flatten()[iMin]

(88, 0.49553767428012752)

### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)



In [252]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

In [260]:
it = np.nditer([A,B,None]) #^?^ None, nditer?; ^?^ what is the meaning of using iterator?
for x,y,z in it: 
    z[...] = x + y
#     z[...] = x.flatten() + y.flatten()
print(it.operands[0],it.operands[1],it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]] [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [256]:
A + B

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [258]:
A.flatten()

array([0, 1, 2])

### 63. Create an array class that has a name attribute (★★☆)

In [265]:
class NamedArray(np.ndarray):  #^?^  python classes 
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [286]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)

In [287]:
Z += np.bincount(I, minlength=len(Z)) #^?^ bicount
print(Z)

[ 2.  4.  3.  1.  1.  2.  3.  5.  6.  3.]


In [288]:
# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1) #add.at
print(Z)

[  3.   7.   5.   1.   1.   3.   5.   9.  11.   5.]


### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [293]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X) #^?^ bincount
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)