In [1]:
import numpy as np

In [2]:
print (np.__version__)


1.12.0


In [3]:
np.show_config() #^?^ show_config()?

blas_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
blas_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/include']
    library_dirs = ['/Users/hanzg/.pyenv/versions/anaconda3-2.5.0/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_mkl_info:
    define_macros = [('SCIPY_MKL_

In [4]:
z = np.zeros(10)

In [5]:
z


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
print (z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [7]:
z = np.zeros((10,10))

In [8]:
z.size

100

In [9]:
z.itemsize

8

In [10]:
print (z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
