# 第2回講義 課題

注意事項：

- 答えを書く欄は Q7の下にあります


- ### 解答を全て書き終わったら Kernel -> Restart -> Restart を押してから Answer Cell がエラーなく実行できる事を確認してください


- ### 答えがわからない時は 'return' として下さい (そのままでよい)


- 各問題の得点配分は以下の通りです

    Q1: 各0.05, Q2: 0.14, Q3: 0.14, Q4: 0.14, Q5:各0.06, Q6: 0.13, Q7: 0.13 (大問7つ 合計 1.0)    


- 関数名は書き換えないで下さい


- 検算には Checker Cell を使用して下さい


- 配列を出力する問題では全て numpy array で出力して下さい


- 配列の入力がある場合は numpy array の入力と仮定して構いません (あえてnp.array(x)などでキャストしなくてもよい)


- 特定のサイズの配列でしか動かないような書き方はしないで下さい　

    解答チェックの際にはここで定義された関数を例とは別のサイズの配列を入力して使用します
     

- 解答提出時には Answer Cell の内容のみを提出してください

In [5]:
import numpy as np


array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

# Q.1
それぞれの結果を与えるコマンドを　A,B,C　から選んで下さい。正解はABCの内一つとは限りません。

### 1
```
array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])
```
```
A
import numpy as np
np.arange(10)//2

B
import numpy as np
(np.arange(5)[:,np.newaxis]*(1,1)).flatten()

C
import numpy as np
np.array([(i,i) for i in range(5)]).flatten()
```


### 2
```
array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])
```
```
A
import numpy as np
x = np.arange(10)
x * (x%2==1)

B
import numpy as np
np.array([i if i%2==0 else 0 for i in range(10)])

C
import numpy as np
np.arange(10) * np.tile([0,1], 5)
```

### 3
```
array([1, 2, 4, 8 ,16])
```
```
A
import numpy as np
2**(np.arange(5))

B
import numpy as np
np.apply_along_axis(np.square, 0, (np.arange(5)))

C
import numpy as np
x = [1]
[x.append(x[i]*2) for i in range(4)]    
np.array(x)
```

### 4
```
array([-1., -1., -1., -1., -1., 1., 1., 1., 1., 1.])
```
```
A
import numpy as np
np.sign(np.arange(10) - 4.5)

B
import numpy as np
np.concatenate([-np.ones(5), np.ones(5)])

C
import numpy as np
(np.arange(10) > 4.5) * 2.0 - 1
```

答えの書き方例
```
Q1_1 = 'A'
Q1_2 = 'B'
Q1_3 = ''
Q1_4 = 'ABC' 
```

# Q2
以下の関数を実装してください。
$$
\sum_k A_{ik} x_k B_{kj} - C_{ji}
$$


例えば
```
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[2,3],[1,2]])
x = np.array([-1, 1, 3])
```
の場合この関数は
```
array([[ 48,  59],
       [ 98, 118]])
```
を与えます。

# Q3
x, a が shape = (N,M), (M,) の numpy array として与えらえれています。

xの各要素をについて、a に近い順に並べ替えて出力する関数を書いてください。

ここで、a, b が近いとはノルム $ \left | a - b \right| = \sqrt{\sum_i \left(a_i - b_i\right)^2}  $ が小さい事を意味します。

例
```
x = np.array([[87, 14], [81, 62], [81, 18], [ 8, 63], [51, 15], [38, 63], [80, 36], [69, 78], [26, 9]])
a = np.array([25, 75]) 
```
として x, y が与えられた時、この関数は
```
array([[38, 63],
       [ 8, 63],
       [69, 78],
       [81, 62],
       [51, 15],
       [26,  9],
       [80, 36],
       [81, 18],
       [87, 14]])
```
を返します

# Q4
M x N の領域に図の用に左上から0, 1, 2,...と番号がふられています。

左からx0+1番目からx1+1番目まで（x1+1番目は含む）

上からy0+1番目からy1+1番目まで（y1+1番目は含む）

の領域にある数字の合計を計算して下さい。

左上はx0=0, y0=0です。


図の例において
x0=1, x1=3, y0=1, y1=2 の時の答えは84です。


```
図
M = 8
N = 6
[  0,   1,  2,  3,  4,  5,  6,  7]
[  8,   9, 10, 11, 12, 13, 14, 15]
[ 16,  17, 18, 19, 20, 21, 22, 23]
[ 24,  25, 26, 27, 28, 29, 30, 31]
[ 32,  33, 34, 35, 36, 37, 38, 39]
[ 40,  41, 42, 43, 44, 45, 46, 47]

x0=1, x1=3, y0=1, y1=2
[ 9, 10, 11]
[17, 18, 19]
sum 84
```

# Q5

category 表現から one-hot 表現を得る関数を作成してください。

またその逆関数も作成して下さい。

category表現とone-hot表現は例えば以下のような関係です。
```
category　[0, 1, 2, 1, 0, 2, 2, 1, 0]
```
```
one-hot
[[ 1., 0., 0.],
[ 0., 1., 0.],
[ 0., 0., 1.],
[ 0., 1., 0.],
[ 1., 0., 0.],
[ 0., 0., 1.],
[ 0., 0., 1.],
[ 0., 1., 0.],
[ 1., 0., 0.]]
```
今、category表現はintegerとして、
one-hotのスロット数はcategory表現の最大値+1とします。(例ではcategoryの最大値が２でone-hotは３スロット)

# Q6
かけ算 $ m \times n $ の表を作って下さい。

for loop は使わずにnumpy.newaxisを使ってください。

例として かけ算 $ 4 \times 5 $ の表は以下のようになります。
```
array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])
```

# Q7
一次元のnumpy array x が与えられた時に xの隣り合った２つの要素の差を与える関数を書きなさい。

例

入力
    array([1,1,2,2,3,4,6,8,9])

出力
    array([0,1,0,1,1,2,2,1])

# Answer Cell

In [178]:
# 答えを書く欄
Q1_1 = 'ABC'
Q1_2 = 'AC'
Q1_3 = 'AC'
Q1_4 = 'ABC'

import numpy as np


def Q2(A, B, C, x):
    """
    Description: 
        matrix-vector calculation
    Arguments: 
        A: matrix l by m (2-dimensional numpy array)
        B: matrix m by n (2-dimensional numpy array)
        C: matrix n by l (2-dimensional numpy array)
        x: vector size m (1-dimensional numpy array)
    Return: 
        A_ik x_k B_kj - C_ji (k-index summed [0 to m-1])
    """
    # CODEME
    return np.einsum('lm,m,mn->nl', A,x,B) - C


def Q3(x, a):
    """
    Description:
        sorting function
    Arguments:
        x: 2-dimensional numpy array
    Return:
        numpy array with the same shape as x
    """
    # CODEME
    return x[np.linalg.norm(x-a,axis = 1).argsort()]


def Q4(M, N, x0, x1, y0, y1):
    """
    Description:
        sum over cropped region
    Arguments:
        M, N, x0, x1, y0, y1: integer
    Return:
        the sum over region in (x0, x1), (y0, y1)
    """
    # CODEME
    return np.arange(M*N).reshape(N,M)[y0:y1+1,x0:x1+1].sum()


def Q5_1(x):
    """
    Description:
        get one-hot expression from category expression
    Arguments:
        x: one-dimensional numpy array, data type integer 
    Return:
        numpy array, one-hot expression of x
    """
    # CODEME
    row = len(x)
    col = x.max()+1
    z = np.zeros(row*col).reshape(row,col)
    z[np.arange(row),x] = 1
    return z


def Q5_2(x):
    """
    Description:
        get category expression from one-hot expression
    Arguments:
        x: numpy array, one-hot expression
    Return:
        one-dimensional numpy array, category expression of x
    """
    # CODEME
    return np.where(x == 1)[1]


def Q6(m, n):
    """
    Description:
        produce multiplication tables m by n
    Arguments:
        m, n: integer
    Return:
        numpy array with shape (m,n)
    """
    # CODEME
    return (np.arange(m)[:,np.newaxis] + 1) * (np.arange(n) + 1)


def Q7(x):
    """
    Arguments:
        x: numpy array 1 dimension
    Return:
        numpy array 1 dimension
        each component is x[i+1] - x[i]  
    """
    # CODEME
    return x[1:] - x[:-1]

# Checker Cell (for student)

In [181]:
# Q2
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[2, 3], [1, 2]])
x = np.array([-1, 1, 3])

Q2(A, B, C, x)

# expected
# array([[ 48,  59],
#       [ 98, 118]])

array([[ 48,  98],
       [ 59, 118]])

In [177]:
# Q3
import numpy as np

x = np.array([[87, 14], [81, 62], [81, 18], [8, 63], [
             51, 15], [38, 63], [80, 36], [69, 78], [26, 9]])
a = np.array([25, 75])

Q3(x, a)

# expected
# array([[38, 63],
#       [ 8, 63],
#       [69, 78],
#       [81, 62],
#       [51, 15],
#       [26,  9],
#       [80, 36],
#       [81, 18],
#       [87, 14]])

array([[38, 63],
       [ 8, 63],
       [69, 78],
       [81, 62],
       [51, 15],
       [26,  9],
       [80, 36],
       [81, 18],
       [87, 14]])

In [155]:
# Q4

M = 8
N = 6
x0 = 1
x1 = 3
y0 = 1
y1 = 2

Q4(M, N, x0, x1, y0, y1)

# expected
# 84

84

In [183]:
# Q5_1
import numpy as np

category = np.array([0, 1, 2, 1, 0, 2, 2, 1, 0])

Q5_1(category)

# expected
# array([[ 1.,  0.,  0.],
#       [ 0.,  1.,  0.],
#       [ 0.,  0.,  1.],
#       [ 0.,  1.,  0.],
#       [ 1.,  0.,  0.],
#       [ 0.,  0.,  1.],
#       [ 0.,  0.,  1.],
#       [ 0.,  1.,  0.],
#       [ 1.,  0.,  0.]])

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [179]:
# Q5_2
import numpy as np

onehot = np.array(
    [[1., 0., 0.],
     [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]])

Q5_2(onehot)

# expected
#array([0, 1, 2, 1, 0, 2, 2, 1, 0])

array([0, 1, 2, 1, 0, 2, 2, 1, 0])

In [131]:
# Q6

Q6(4, 5)

# expected
# array([[ 1,  2,  3,  4],
#       [ 2,  4,  6,  8],
#       [ 3,  6,  9, 12],
#       [ 4,  8, 12, 16],
#       [ 5, 10, 15, 20]])

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20]])

In [26]:
# Q7

import numpy as np
v = np.array([1, 1, 2, 2, 3, 4, 6, 8, 9])

Q7(v)

# expected
#array([0, 1, 0, 1, 1, 2, 2, 1])

array([0, 1, 0, 1, 1, 2, 2, 1])